import type { Court } from '@/types'
import { generateId } from './utils'

export function getPakistaniCourts(): Court[] {
  return [
    // ===== SUPREME COURT OF PAKISTAN =====
    {
      id: 'sc-pk',
      name: 'Supreme Court of Pakistan',
      type: 'Supreme Court',
      level: 'apex',
      parent_id: null,
      city: 'Islamabad',
      province: 'Islamabad',
    },
    {
      id: 'sc-lhr-bench',
      name: 'Supreme Court of Pakistan - Lahore Registry',
      type: 'Supreme Court Bench',
      level: 'apex',
      parent_id: 'sc-pk',
      city: 'Lahore',
      province: 'Punjab',
    },
    {
      id: 'sc-khi-bench',
      name: 'Supreme Court of Pakistan - Karachi Registry',
      type: 'Supreme Court Bench',
      level: 'apex',
      parent_id: 'sc-pk',
      city: 'Karachi',
      province: 'Sindh',
    },
    {
      id: 'sc-pew-bench',
      name: 'Supreme Court of Pakistan - Peshawar Registry',
      type: 'Supreme Court Bench',
      level: 'apex',
      parent_id: 'sc-pk',
      city: 'Peshawar',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'sc-qta-bench',
      name: 'Supreme Court of Pakistan - Quetta Registry',
      type: 'Supreme Court Bench',
      level: 'apex',
      parent_id: 'sc-pk',
      city: 'Quetta',
      province: 'Balochistan',
    },

    // ===== LAHORE HIGH COURT =====
    {
      id: 'hc-lhr',
      name: 'Lahore High Court',
      type: 'High Court',
      level: 'high',
      parent_id: null,
      city: 'Lahore',
      province: 'Punjab',
    },
    {
      id: 'hc-lhr-rawalpindi',
      name: 'Lahore High Court - Rawalpindi Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-lhr',
      city: 'Rawalpindi',
      province: 'Punjab',
    },
    {
      id: 'hc-lhr-multan',
      name: 'Lahore High Court - Multan Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-lhr',
      city: 'Multan',
      province: 'Punjab',
    },
    {
      id: 'hc-lhr-bahawalpur',
      name: 'Lahore High Court - Bahawalpur Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-lhr',
      city: 'Bahawalpur',
      province: 'Punjab',
    },
    {
      id: 'hc-lhr-gujranwala',
      name: 'Lahore High Court - Gujranwala Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-lhr',
      city: 'Gujranwala',
      province: 'Punjab',
    },
    {
      id: 'hc-lhr-sialkot',
      name: 'Lahore High Court - Sialkot Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-lhr',
      city: 'Sialkot',
      province: 'Punjab',
    },

    // ===== SINDH HIGH COURT =====
    {
      id: 'hc-sindh',
      name: 'Sindh High Court',
      type: 'High Court',
      level: 'high',
      parent_id: null,
      city: 'Karachi',
      province: 'Sindh',
    },
    {
      id: 'hc-sindh-sukkur',
      name: 'Sindh High Court - Sukkur Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-sindh',
      city: 'Sukkur',
      province: 'Sindh',
    },
    {
      id: 'hc-sindh-hyderabad',
      name: 'Sindh High Court - Hyderabad Circuit',
      type: 'High Court Circuit',
      level: 'high',
      parent_id: 'hc-sindh',
      city: 'Hyderabad',
      province: 'Sindh',
    },
    {
      id: 'hc-sindh-larkana',
      name: 'Sindh High Court - Larkana Circuit',
      type: 'High Court Circuit',
      level: 'high',
      parent_id: 'hc-sindh',
      city: 'Larkana',
      province: 'Sindh',
    },

    // ===== PESHAWAR HIGH COURT =====
    {
      id: 'hc-peshawar',
      name: 'Peshawar High Court',
      type: 'High Court',
      level: 'high',
      parent_id: null,
      city: 'Peshawar',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'hc-peshawar-mingora',
      name: 'Peshawar High Court - Mingora Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-peshawar',
      city: 'Mingora',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'hc-peshawar-abbottabad',
      name: 'Peshawar High Court - Abbottabad Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-peshawar',
      city: 'Abbottabad',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'hc-peshawar-bannu',
      name: 'Peshawar High Court - Bannu Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-peshawar',
      city: 'Bannu',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'hc-peshawar-deraismailkhan',
      name: 'Peshawar High Court - Dera Ismail Khan Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-peshawar',
      city: 'Dera Ismail Khan',
      province: 'Khyber Pakhtunkhwa',
    },

    // ===== BALOCHISTAN HIGH COURT =====
    {
      id: 'hc-balochistan',
      name: 'Balochistan High Court',
      type: 'High Court',
      level: 'high',
      parent_id: null,
      city: 'Quetta',
      province: 'Balochistan',
    },
    {
      id: 'hc-balochistan-sibi',
      name: 'Balochistan High Court - Sibi Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-balochistan',
      city: 'Sibi',
      province: 'Balochistan',
    },
    {
      id: 'hc-balochistan-khuzdar',
      name: 'Balochistan High Court - Khuzdar Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-balochistan',
      city: 'Khuzdar',
      province: 'Balochistan',
    },
    {
      id: 'hc-balochistan-turbat',
      name: 'Balochistan High Court - Turbat Bench',
      type: 'High Court Bench',
      level: 'high',
      parent_id: 'hc-balochistan',
      city: 'Turbat',
      province: 'Balochistan',
    },

    // ===== ISLAMABAD HIGH COURT =====
    {
      id: 'hc-islamabad',
      name: 'Islamabad High Court',
      type: 'High Court',
      level: 'high',
      parent_id: null,
      city: 'Islamabad',
      province: 'Islamabad',
    },

    // ===== PUNJAB DISTRICT COURTS =====
    {
      id: 'dc-lahore',
      name: 'District & Sessions Court Lahore',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Lahore',
      province: 'Punjab',
    },
    {
      id: 'dc-rawalpindi',
      name: 'District & Sessions Court Rawalpindi',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Rawalpindi',
      province: 'Punjab',
    },
    {
      id: 'dc-faisalabad',
      name: 'District & Sessions Court Faisalabad',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Faisalabad',
      province: 'Punjab',
    },
    {
      id: 'dc-multan',
      name: 'District & Sessions Court Multan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Multan',
      province: 'Punjab',
    },
    {
      id: 'dc-gujranwala',
      name: 'District & Sessions Court Gujranwala',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Gujranwala',
      province: 'Punjab',
    },
    {
      id: 'dc-bahawalpur',
      name: 'District & Sessions Court Bahawalpur',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Bahawalpur',
      province: 'Punjab',
    },
    {
      id: 'dc-sargodha',
      name: 'District & Sessions Court Sargodha',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Sargodha',
      province: 'Punjab',
    },
    {
      id: 'dc-sialkot',
      name: 'District & Sessions Court Sialkot',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Sialkot',
      province: 'Punjab',
    },
    {
      id: 'dc-sheikhupura',
      name: 'District & Sessions Court Sheikhupura',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Sheikhupura',
      province: 'Punjab',
    },
    {
      id: 'dc-gujrat',
      name: 'District & Sessions Court Gujrat',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Gujrat',
      province: 'Punjab',
    },
    {
      id: 'dc-jhelum',
      name: 'District & Sessions Court Jhelum',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Jhelum',
      province: 'Punjab',
    },
    {
      id: 'dc-mianwali',
      name: 'District & Sessions Court Mianwali',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Mianwali',
      province: 'Punjab',
    },
    {
      id: 'dc-attock',
      name: 'District & Sessions Court Attock',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Attock',
      province: 'Punjab',
    },
    {
      id: 'dc-chakwal',
      name: 'District & Sessions Court Chakwal',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Chakwal',
      province: 'Punjab',
    },
    {
      id: 'dc-sahiwal',
      name: 'District & Sessions Court Sahiwal',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Sahiwal',
      province: 'Punjab',
    },
    {
      id: 'dc-okara',
      name: 'District & Sessions Court Okara',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Okara',
      province: 'Punjab',
    },
    {
      id: 'dc-pakpattan',
      name: 'District & Sessions Court Pakpattan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Pakpattan',
      province: 'Punjab',
    },
    {
      id: 'dc-vehari',
      name: 'District & Sessions Court Vehari',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Vehari',
      province: 'Punjab',
    },
    {
      id: 'dc-khanewal',
      name: 'District & Sessions Court Khanewal',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Khanewal',
      province: 'Punjab',
    },
    {
      id: 'dc-lodhran',
      name: 'District & Sessions Court Lodhran',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Lodhran',
      province: 'Punjab',
    },
    {
      id: 'dc-dg khan',
      name: 'District & Sessions Court Dera Ghazi Khan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Dera Ghazi Khan',
      province: 'Punjab',
    },
    {
      id: 'dc-rajanpur',
      name: 'District & Sessions Court Rajanpur',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Rajanpur',
      province: 'Punjab',
    },
    {
      id: 'dc-muzaffargarh',
      name: 'District & Sessions Court Muzaffargarh',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Muzaffargarh',
      province: 'Punjab',
    },
    {
      id: 'dc-leiah',
      name: 'District & Sessions Court Layyah',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Layyah',
      province: 'Punjab',
    },
    {
      id: 'dc-bhakkar',
      name: 'District & Sessions Court Bhakkar',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Bhakkar',
      province: 'Punjab',
    },
    {
      id: 'dc-khushab',
      name: 'District & Sessions Court Khushab',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Khushab',
      province: 'Punjab',
    },
    {
      id: 'dc-jhang',
      name: 'District & Sessions Court Jhang',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Jhang',
      province: 'Punjab',
    },
    {
      id: 'dc-ttsingh',
      name: 'District & Sessions Court Toba Tek Singh',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Toba Tek Singh',
      province: 'Punjab',
    },
    {
      id: 'dc-chiniot',
      name: 'District & Sessions Court Chiniot',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Chiniot',
      province: 'Punjab',
    },
    {
      id: 'dc-hafizabad',
      name: 'District & Sessions Court Hafizabad',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Hafizabad',
      province: 'Punjab',
    },
    {
      id: 'dc-mbdeen',
      name: 'District & Sessions Court Mandi Bahauddin',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Mandi Bahauddin',
      province: 'Punjab',
    },
    {
      id: 'dc-narowal',
      name: 'District & Sessions Court Narowal',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Narowal',
      province: 'Punjab',
    },
    {
      id: 'dc-kasur',
      name: 'District & Sessions Court Kasur',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Kasur',
      province: 'Punjab',
    },
    {
      id: 'dc-nankana',
      name: 'District & Sessions Court Nankana Sahib',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Nankana Sahib',
      province: 'Punjab',
    },
    {
      id: 'dc-rrykhan',
      name: 'District & Sessions Court Rahim Yar Khan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Rahim Yar Khan',
      province: 'Punjab',
    },
    {
      id: 'dc-bhakkar2',
      name: 'District & Sessions Court Bahawalnagar',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Bahawalnagar',
      province: 'Punjab',
    },
    {
      id: 'dc-sadiqabad',
      name: 'District & Sessions Court Rahim Yar Khan (Sadiqabad)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-lhr',
      city: 'Sadiqabad',
      province: 'Punjab',
    },

    // ===== SINDH DISTRICT COURTS =====
    {
      id: 'dc-karachi-central',
      name: 'District & Sessions Court Karachi Central',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Karachi',
      province: 'Sindh',
    },
    {
      id: 'dc-karachi-east',
      name: 'District & Sessions Court Karachi East',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Karachi',
      province: 'Sindh',
    },
    {
      id: 'dc-karachi-west',
      name: 'District & Sessions Court Karachi West',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Karachi',
      province: 'Sindh',
    },
    {
      id: 'dc-karachi-south',
      name: 'District & Sessions Court Karachi South',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Karachi',
      province: 'Sindh',
    },
    {
      id: 'dc-karachi-malir',
      name: 'District & Sessions Court Karachi Malir',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Karachi',
      province: 'Sindh',
    },
    {
      id: 'dc-hyderabad',
      name: 'District & Sessions Court Hyderabad',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Hyderabad',
      province: 'Sindh',
    },
    {
      id: 'dc-sukkur',
      name: 'District & Sessions Court Sukkur',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Sukkur',
      province: 'Sindh',
    },
    {
      id: 'dc-larkana',
      name: 'District & Sessions Court Larkana',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Larkana',
      province: 'Sindh',
    },
    {
      id: 'dc-nawabshah',
      name: 'District & Sessions Court Nawabshah (Shaheed Benazirabad)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Nawabshah',
      province: 'Sindh',
    },
    {
      id: 'dc-mirpurkhas',
      name: 'District & Sessions Court Mirpurkhas',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Mirpurkhas',
      province: 'Sindh',
    },
    {
      id: 'dc-khairpur',
      name: 'District & Sessions Court Khairpur',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Khairpur',
      province: 'Sindh',
    },
    {
      id: 'dc-tharparkar',
      name: 'District & Sessions Court Tharparkar (Mithi)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Mithi',
      province: 'Sindh',
    },
    {
      id: 'dc-umarkot',
      name: 'District & Sessions Court Umarkot',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Umarkot',
      province: 'Sindh',
    },
    {
      id: 'dc-badin',
      name: 'District & Sessions Court Badin',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Badin',
      province: 'Sindh',
    },
    {
      id: 'dc-thatta',
      name: 'District & Sessions Court Thatta',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Thatta',
      province: 'Sindh',
    },
    {
      id: 'dc-sujawal',
      name: 'District & Sessions Court Sujawal',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Sujawal',
      province: 'Sindh',
    },
    {
      id: 'dc-dadu',
      name: 'District & Sessions Court Dadu',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Dadu',
      province: 'Sindh',
    },
    {
      id: 'dc-jamshoro',
      name: 'District & Sessions Court Jamshoro',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Jamshoro',
      province: 'Sindh',
    },
    {
      id: 'dc-ghotki',
      name: 'District & Sessions Court Ghotki',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Ghotki',
      province: 'Sindh',
    },
    {
      id: 'dc-kashmore',
      name: 'District & Sessions Court Kashmore',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Kashmore',
      province: 'Sindh',
    },
    {
      id: 'dc-jacobabad',
      name: 'District & Sessions Court Jacobabad',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Jacobabad',
      province: 'Sindh',
    },
    {
      id: 'dc-shikarpur',
      name: 'District & Sessions Court Shikarpur',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Shikarpur',
      province: 'Sindh',
    },
    {
      id: 'dc-kambar',
      name: 'District & Sessions Court Kamber Shahdadkot',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Kamber',
      province: 'Sindh',
    },
    {
      id: 'dc-sanghar',
      name: 'District & Sessions Court Sanghar',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Sanghar',
      province: 'Sindh',
    },
    {
      id: 'dc-tandoallahyar',
      name: 'District & Sessions Court Tando Allahyar',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Tando Allahyar',
      province: 'Sindh',
    },
    {
      id: 'dc-tandomuhammadkhan',
      name: 'District & Sessions Court Tando Muhammad Khan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Tando Muhammad Khan',
      province: 'Sindh',
    },
    {
      id: 'dc-matiari',
      name: 'District & Sessions Court Matiari',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-sindh',
      city: 'Matiari',
      province: 'Sindh',
    },

    // ===== KPK DISTRICT COURTS =====
    {
      id: 'dc-peshawar',
      name: 'District & Sessions Court Peshawar',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Peshawar',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-abbottabad',
      name: 'District & Sessions Court Abbottabad',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Abbottabad',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-mardan',
      name: 'District & Sessions Court Mardan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Mardan',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-swabi',
      name: 'District & Sessions Court Swabi',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Swabi',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-kohat',
      name: 'District & Sessions Court Kohat',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Kohat',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-bannu',
      name: 'District & Sessions Court Bannu',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Bannu',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-deraismailkhan',
      name: 'District & Sessions Court Dera Ismail Khan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Dera Ismail Khan',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-swat',
      name: 'District & Sessions Court Swat (Mingora)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Mingora',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-chitral',
      name: 'District & Sessions Court Chitral',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Chitral',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-dirupper',
      name: 'District & Sessions Court Dir Upper',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Dir',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-dirlower',
      name: 'District & Sessions Court Dir Lower',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Dir',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-mansehra',
      name: 'District & Sessions Court Mansehra',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Mansehra',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-battagram',
      name: 'District & Sessions Court Battagram',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Battagram',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-kohistan',
      name: 'District & Sessions Court Kohistan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Dasu',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-torghar',
      name: 'District & Sessions Court Torghar',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Torghar',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-haripur',
      name: 'District & Sessions Court Haripur',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Haripur',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-nowshera',
      name: 'District & Sessions Court Nowshera',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Nowshera',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-charsadda',
      name: 'District & Sessions Court Charsadda',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Charsadda',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-karak',
      name: 'District & Sessions Court Karak',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Karak',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-hangu',
      name: 'District & Sessions Court Hangu',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Hangu',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-omal',
      name: 'District & Sessions Court Orakzai',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Orakzai',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-kurram',
      name: 'District & Sessions Court Kurram (Parachinar)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Parachinar',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-tank',
      name: 'District & Sessions Court Tank',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Tank',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-lakkimarwat',
      name: 'District & Sessions Court Lakki Marwat',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Lakki Marwat',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-shangla',
      name: 'District & Sessions Court Shangla',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Shangla',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-buner',
      name: 'District & Sessions Court Buner',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Buner',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-malakand',
      name: 'District & Sessions Court Malakand (Batkhela)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Batkhela',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-bajaur',
      name: 'District & Sessions Court Bajaur (Khar)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Khar',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-mohmand',
      name: 'District & Sessions Court Mohmand (Ghalanai)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Ghalanai',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-khyber',
      name: 'District & Sessions Court Khyber (Landi Kotal)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Landi Kotal',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-nwaziristan',
      name: 'District & Sessions Court North Waziristan (Miranshah)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Miranshah',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'dc-swaziristan',
      name: 'District & Sessions Court South Waziristan (Wana)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-peshawar',
      city: 'Wana',
      province: 'Khyber Pakhtunkhwa',
    },

    // ===== BALOCHISTAN DISTRICT COURTS =====
    {
      id: 'dc-quetta',
      name: 'District & Sessions Court Quetta',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Quetta',
      province: 'Balochistan',
    },
    {
      id: 'dc-pishin',
      name: 'District & Sessions Court Pishin',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Pishin',
      province: 'Balochistan',
    },
    {
      id: 'dc-killaabdullah',
      name: 'District & Sessions Court Killa Abdullah',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Chaman',
      province: 'Balochistan',
    },
    {
      id: 'dc-killasaifullah',
      name: 'District & Sessions Court Killa Saifullah',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Killa Saifullah',
      province: 'Balochistan',
    },
    {
      id: 'dc-zhob',
      name: 'District & Sessions Court Zhob',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Zhob',
      province: 'Balochistan',
    },
    {
      id: 'dc-sherani',
      name: 'District & Sessions Court Sherani',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Sherani',
      province: 'Balochistan',
    },
    {
      id: 'dc-musakhail',
      name: 'District & Sessions Court Musakhail',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Musakhail',
      province: 'Balochistan',
    },
    {
      id: 'dc-barkhan',
      name: 'District & Sessions Court Barkhan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Barkhan',
      province: 'Balochistan',
    },
    {
      id: 'dc-loralai',
      name: 'District & Sessions Court Loralai',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Loralai',
      province: 'Balochistan',
    },
    {
      id: 'dc-dukki',
      name: 'District & Sessions Court Dukki',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Dukki',
      province: 'Balochistan',
    },
    {
      id: 'dc-ziarat',
      name: 'District & Sessions Court Ziarat',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Ziarat',
      province: 'Balochistan',
    },
    {
      id: 'dc-sibi',
      name: 'District & Sessions Court Sibi',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Sibi',
      province: 'Balochistan',
    },
    {
      id: 'dc-harnai',
      name: 'District & Sessions Court Harnai',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Harnai',
      province: 'Balochistan',
    },
    {
      id: 'dc-kohlu',
      name: 'District & Sessions Court Kohlu',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Kohlu',
      province: 'Balochistan',
    },
    {
      id: 'dc-derabugti',
      name: 'District & Sessions Court Dera Bugti',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Dera Bugti',
      province: 'Balochistan',
    },
    {
      id: 'dc-nasirabad',
      name: 'District & Sessions Court Nasirabad (Dera Murad Jamali)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Dera Murad Jamali',
      province: 'Balochistan',
    },
    {
      id: 'dc-jaffarabad',
      name: 'District & Sessions Court Jaffarabad',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Jaffarabad',
      province: 'Balochistan',
    },
    {
      id: 'dc-ustamuhammad',
      name: 'District & Sessions Court Usta Muhammad',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Usta Muhammad',
      province: 'Balochistan',
    },
    {
      id: 'dc-sohbatpur',
      name: 'District & Sessions Court Sohbatpur',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Sohbatpur',
      province: 'Balochistan',
    },
    {
      id: 'dc-jhalmagsi',
      name: 'District & Sessions Court Jhal Magsi',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Jhal Magsi',
      province: 'Balochistan',
    },
    {
      id: 'dc-kachhi',
      name: 'District & Sessions Court Kachhi (Bolan)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Dhadar',
      province: 'Balochistan',
    },
    {
      id: 'dc-kalat',
      name: 'District & Sessions Court Kalat',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Kalat',
      province: 'Balochistan',
    },
    {
      id: 'dc-mastung',
      name: 'District & Sessions Court Mastung',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Mastung',
      province: 'Balochistan',
    },
    {
      id: 'dc-khuzdar',
      name: 'District & Sessions Court Khuzdar',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Khuzdar',
      province: 'Balochistan',
    },
    {
      id: 'dc-awaran',
      name: 'District & Sessions Court Awaran',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Awaran',
      province: 'Balochistan',
    },
    {
      id: 'dc-washuk',
      name: 'District & Sessions Court Washuk',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Washuk',
      province: 'Balochistan',
    },
    {
      id: 'dc-kharan',
      name: 'District & Sessions Court Kharan',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Kharan',
      province: 'Balochistan',
    },
    {
      id: 'dc-chagai',
      name: 'District & Sessions Court Chagai (Dalbandin)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Dalbandin',
      province: 'Balochistan',
    },
    {
      id: 'dc-nokundi',
      name: 'District & Sessions Court Nokundi',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Nokundi',
      province: 'Balochistan',
    },
    {
      id: 'dc-punjgur',
      name: 'District & Sessions Court Panjgur',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Panjgur',
      province: 'Balochistan',
    },
    {
      id: 'dc-turbat',
      name: 'District & Sessions Court Kech (Turbat)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Turbat',
      province: 'Balochistan',
    },
    {
      id: 'dc-gwadar',
      name: 'District & Sessions Court Gwadar',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Gwadar',
      province: 'Balochistan',
    },
    {
      id: 'dc-lasbela',
      name: 'District & Sessions Court Lasbela (Uthal)',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Uthal',
      province: 'Balochistan',
    },
    {
      id: 'dc-hub',
      name: 'District & Sessions Court Hub',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-balochistan',
      city: 'Hub',
      province: 'Balochistan',
    },

    // ===== ISLAMABAD COURTS =====
    {
      id: 'dc-islamabad',
      name: 'District & Sessions Court Islamabad',
      type: 'District Court',
      level: 'district',
      parent_id: 'hc-islamabad',
      city: 'Islamabad',
      province: 'Islamabad',
    },

    // ===== SPECIAL COURTS =====
    {
      id: 'sc-ata',
      name: 'Anti-Terrorism Court',
      type: 'Special Court',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'sc-ata-lhr',
      name: 'Anti-Terrorism Court Lahore',
      type: 'Special Court',
      level: 'special',
      parent_id: 'sc-ata',
      city: 'Lahore',
      province: 'Punjab',
    },
    {
      id: 'sc-ata-khi',
      name: 'Anti-Terrorism Court Karachi',
      type: 'Special Court',
      level: 'special',
      parent_id: 'sc-ata',
      city: 'Karachi',
      province: 'Sindh',
    },
    {
      id: 'sc-ata-rawalpindi',
      name: 'Anti-Terrorism Court Rawalpindi',
      type: 'Special Court',
      level: 'special',
      parent_id: 'sc-ata',
      city: 'Rawalpindi',
      province: 'Punjab',
    },
    {
      id: 'sc-ata-pew',
      name: 'Anti-Terrorism Court Peshawar',
      type: 'Special Court',
      level: 'special',
      parent_id: 'sc-ata',
      city: 'Peshawar',
      province: 'Khyber Pakhtunkhwa',
    },
    {
      id: 'sc-ata-qta',
      name: 'Anti-Terrorism Court Quetta',
      type: 'Special Court',
      level: 'special',
      parent_id: 'sc-ata',
      city: 'Quetta',
      province: 'Balochistan',
    },
    {
      id: 'family-court',
      name: 'Family Court',
      type: 'Special Court',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'banking-court',
      name: 'Banking Court',
      type: 'Special Court',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'customs-court',
      name: 'Customs Court',
      type: 'Special Court',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'federal-service-tribunal',
      name: 'Federal Service Tribunal',
      type: 'Tribunal',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'provincial-service-tribunal',
      name: 'Provincial Service Tribunal',
      type: 'Tribunal',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'income-tax-tribunal',
      name: 'Income Tax Appellate Tribunal',
      type: 'Tribunal',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'environment-tribunal',
      name: 'Environmental Tribunal',
      type: 'Tribunal',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'drugs-court',
      name: 'Control of Narcotics Substances Court',
      type: 'Special Court',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'labour-court',
      name: 'Labour Court',
      type: 'Special Court',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
    {
      id: 'child-court',
      name: 'Child Protection Court',
      type: 'Special Court',
      level: 'special',
      parent_id: null,
      city: '',
      province: '',
    },
  ]
}
