import { jsPDF } from 'jspdf'
import type { LawyerProfile, DiaryEntry, Case, Court, Proceeding } from '@/types'
import { getPakistaniCourts } from './court-data'
import { db } from './db'

const allCourts = getPakistaniCourts()

function getCourtName(id: string | null | undefined): string {
  if (!id) return ''
  const court = allCourts.find((c) => c.id === id)
  return court ? `${court.name}${court.city ? `, ${court.city}` : ''}` : id
}

async function getLawyer(): Promise<LawyerProfile | null> {
  return db.getLawyerProfile()
}

export async function exportDiaryPdf(
  entries: DiaryEntry[],
  dateLabel: string
): Promise<void> {
  const lawyer = await getLawyer()
  const doc = new jsPDF('p', 'mm', 'a4')
  const pageW = 210
  const margin = 20
  const contentW = pageW - margin * 2
  let y = margin

  function addHeader() {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(16)
    doc.text('LEGAL LAW DIARY', pageW / 2, y, { align: 'center' })
    y += 7

    if (lawyer) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.text(`Advocate: ${lawyer.full_name}`, margin, y)
      y += 5
      doc.setFontSize(9)
      doc.text(`License #: ${lawyer.bar_council}-${lawyer.license_number}`, margin, y)
      y += 4
      doc.text(`Mobile: ${lawyer.mobile_number}`, margin, y)
      y += 4
      if (lawyer.chamber_address) {
        doc.text(`Chamber: ${lawyer.chamber_address}`, margin, y)
        y += 4
      }
    }
    y += 3

    doc.setDrawColor(0, 102, 204)
    doc.setLineWidth(0.5)
    doc.line(margin, y, pageW - margin, y)
    y += 6
  }

  function addFooter(pageNum: number) {
    const fy = 290
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.setFont('helvetica', 'italic')
    doc.text(`Generated by Legal Law Diary - Page ${pageNum}`, pageW / 2, fy, {
      align: 'center',
    })
    doc.setTextColor(0)
  }

  addHeader()

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text(`Case Diary - ${dateLabel}`, margin, y)
  y += 6

  if (entries.length === 0) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text('No entries for this period.', margin, y)
    y += 6
  } else {
    const tableTop = y
    const colW = [12, 40, 50, 20, 60]
    const colX: number[] = []
    let cx = margin
    for (const w of colW) {
      colX.push(cx)
      cx += w
    }

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(255)
    doc.setFillColor(0, 102, 204)
    const headers = ['#', 'Date', 'Case', 'Status', 'Purpose']
    doc.rect(margin, y, contentW, 6, 'F')
    headers.forEach((h, i) => {
      doc.text(h, colX[i] + 1, y + 4)
    })
    y += 8
    doc.setTextColor(0)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)

    entries.forEach((entry, idx) => {
      if (y > 270) {
        addFooter(1)
        doc.addPage()
        y = margin
        addHeader()
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(8)
      }

      if (idx % 2 === 0) {
        doc.setFillColor(245, 248, 252)
        doc.rect(margin, y - 1, contentW, 5, 'F')
      }

      doc.text(String(idx + 1), colX[0] + 1, y + 3)
      doc.text(entry.date.slice(0, 10), colX[1] + 1, y + 3)

      const caseNum = entry.case_id.length > 18
        ? entry.case_id.slice(0, 16) + '..'
        : entry.case_id
      doc.text(caseNum, colX[2] + 1, y + 3)
      doc.text(entry.status, colX[3] + 1, y + 3)

      const purpose = entry.purpose ?? ''
      const purposeText = purpose.length > 24
        ? purpose.slice(0, 22) + '..'
        : purpose
      doc.text(purposeText, colX[4] + 1, y + 3)

      y += 5
    })

    y += 4
  }

  addFooter(1)
  doc.save(`diary-${dateLabel.replace(/\s+/g, '-').toLowerCase()}.pdf`)
}

export async function exportCasePdf(
  caseData: Case,
  proceedings: Proceeding[],
  courtName: string
): Promise<void> {
  const lawyer = await getLawyer()
  const doc = new jsPDF('p', 'mm', 'a4')
  const pageW = 210
  const margin = 20
  const contentW = pageW - margin * 2
  let y = margin

  function addHeader() {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(16)
    doc.text('LEGAL LAW DIARY', pageW / 2, y, { align: 'center' })
    y += 7

    if (lawyer) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.text(`Advocate: ${lawyer.full_name}`, margin, y)
      y += 5
      doc.setFontSize(9)
      doc.text(`License #: ${lawyer.bar_council}-${lawyer.license_number}`, margin, y)
      y += 4
      doc.text(`Mobile: ${lawyer.mobile_number}`, margin, y)
      y += 4
      if (lawyer.chamber_address) {
        doc.text(`Chamber: ${lawyer.chamber_address}`, margin, y)
        y += 4
      }
    }
    y += 3

    doc.setDrawColor(0, 102, 204)
    doc.setLineWidth(0.5)
    doc.line(margin, y, pageW - margin, y)
    y += 6
  }

  function addFooter(pageNum: number) {
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.setFont('helvetica', 'italic')
    doc.text(`Generated by Legal Law Diary - Page ${pageNum}`, pageW / 2, 290, {
      align: 'center',
    })
    doc.setTextColor(0)
  }

  addHeader()

  // Case Details
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('Case Summary', margin, y)
  y += 7

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const fields = [
    ['Case Number:', caseData.case_number],
    ['Title:', caseData.title],
    ['Case Type:', caseData.case_type ?? 'N/A'],
    ['Division:', caseData.division ?? 'N/A'],
    ['Filing Date:', caseData.filing_date ?? 'N/A'],
    ['Status:', caseData.status],
    ['Court:', courtName || 'N/A'],
  ]

  const labelW = 30
  fields.forEach(([label, value]) => {
    if (y > 270) {
      addFooter(1)
      doc.addPage()
      y = margin
      addHeader()
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
    }

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.text(value, margin + labelW, y)
    y += 5.5
  })

  if (caseData.description) {
    y += 2
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.text('Description:', margin, y)
    y += 4
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(caseData.description, contentW)
    lines.forEach((line: string) => {
      if (y > 270) {
        addFooter(1)
        doc.addPage()
        y = margin
      }
      doc.text(line, margin, y)
      y += 4
    })
  }

  // Proceedings
  if (proceedings.length > 0) {
    y += 4
    doc.setDrawColor(0, 102, 204)
    doc.setLineWidth(0.3)
    doc.line(margin, y, pageW - margin, y)
    y += 6

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text('Proceedings', margin, y)
    y += 6

    const procColW = [8, 22, 25, 120]
    const procColX: number[] = []
    let cx = margin
    for (const w of procColW) {
      procColX.push(cx)
      cx += w
    }

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(255)
    doc.setFillColor(0, 102, 204)
    doc.rect(margin, y, contentW, 5, 'F')
    ;['#', 'Date', 'Type', 'Summary'].forEach((h, i) => {
      doc.text(h, procColX[i] + 1, y + 3.5)
    })
    y += 7
    doc.setTextColor(0)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)

    proceedings.forEach((p, idx) => {
      if (y > 265) {
        addFooter(1)
        doc.addPage()
        y = margin
        addHeader()
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(8)
      }

      if (idx % 2 === 0) {
        doc.setFillColor(245, 248, 252)
        doc.rect(margin, y - 1, contentW, 5, 'F')
      }

      doc.text(String(idx + 1), procColX[0] + 1, y + 3)
      doc.text((p.date || '').slice(0, 10), procColX[1] + 1, y + 3)
      doc.text((p.proceeding_type ?? '').slice(0, 12), procColX[2] + 1, y + 3)

      const summary = p.order_summary ?? ''
      const lines = doc.splitTextToSize(summary, procColW[3] - 2)
      doc.text(lines.slice(0, 1), procColX[3] + 1, y + 3)

      y += 5
    })
  }

  addFooter(1)
  const filename = `case-${caseData.case_number.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}.pdf`
  doc.save(filename)
}
